name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8.10
        uses: actions/setup-python@v1
        with:
          python-version: 3.8.10
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r black mypy flake8
      - name: Lint with flake8
        run: |
          flake8 .
      - name: Check formatting with black
        run: |
          black --check .
      - name: Check typehints with mypy
        run: |
          mypy .
      - name: Test with pytest
        run: |
          pytest
